product/InspectorGadget/grails-app/domain/inspector/gadget/job/Job.groovy
package inspector.gadget.job

import inspector.gadget.Application
import model.JobCriticity
import model.execution.CronExecutionStrategy
import model.execution.IntervalExecutionStrategy
import org.quartz.CronExpression

class Job {
    transient def notificationService
    String name
    String description
    Long warningDurationThreshold
    Long errorDurationThreshold
    Long executionInterval

    String executionRegExp
    Boolean usesRegExp = Boolean.FALSE

    Boolean enabled = false
    Configuration configuration
    Application application
    JobCriticity criticity = JobCriticity.MEDIUM

    String escalationSteps = "None"
    Date dateCreated
    Date lastUpdated

    static constraints = {
        name(nullable: false, blank: false, unique: true)
        description(nullable: true)
        errorDurationThreshold(nullable: false, min: 0l, max: Long.MAX_VALUE)
        warningDurationThreshold(nullable: false, min: 0l, max: Long.MAX_VALUE)
        enabled(nullable: false)
        application(nullable: false)
        configuration(nullable: false)
        criticity(nullable: false, blank: false)
        executionInterval(nullable: true, min: 0l, max: Long.MAX_VALUE)
        escalationSteps(nullable: false, blank: false, minSize: 0, widget: 'textarea')
        usesRegExp(nullable: false)
        executionRegExp(nullable: true, dateCron: true, maxSize: 100, minSize: 0, validator:  { val, obj ->
            if (obj.usesRegExp) {
                return (obj.executionRegExp != null && !obj.executionRegExp?.isEmpty())
            } else {
                return obj.executionInterval > 0
            }
        })
    }

    static mapping = {
        table 'T_JOB'
        version false
        id(column: 'P_ID')
        name(column: 'A_NAME')
        description(column: 'A_DESCRIPTION')
        warningDurationThreshold(column: 'A_WARN_DURATION_THRESHOLD_IN_SECONDS')
        errorDurationThreshold(column: 'A_ERROR_DURATION_THRESHOLD_IN_SECONDS')
        executionInterval(column: 'A_EXECUTION_INTERVAL_IN_SECONDS')
        enabled(column: 'A_IS_ENABLED')
        application(column: 'F_APPLICATION_ID')
        configuration(column: 'F_CONFIGURATION_ID')
        criticity(column: 'A_CRITICITY')
        dateCreated(column: 'A_CREATION_DATE')
        lastUpdated(column: 'A_LAST_UPDATE_DATE')
        usesRegExp(column: 'A_USES_REG_EXP')
        executionRegExp(column: 'A_EXECUTION_REG_EXP')
        escalationSteps(column: 'A_ESCALATION_STEPS', type: 'text')
    }

    String toString() {
        return name
    }

    def shouldHaveStarted() {
        return getExecutionStrategy().shouldHaveStarted()
    }

    def shouldHaveFinish(JobInstance instance) {
        return getExecutionStrategy().shouldHaveFinished(instance)
    }

    Boolean hasInstances() {
        return JobInstance.countByJob(this) > 0
    }

    def beforeInsert() {
        if ( usesRegExp ) {
            executionInterval = 0l
        }
    }

    def afterInsert() {
        notificationService.fireJobCreationNotification(this)
    }

    def didNotStartNewInstance() {
        def now = Calendar.getInstance().getTime()
        def failedInstance = new JobInstance(job: this, startedAt: now, endedAt: now)
        failedInstance.error("Job (id=${this.id}) did not start a new instance")

        notificationService.fireNoStartupNotification(this)
    }

    def getExecutionRegExAsCronExpression() {
        return new CronExpression(this.executionRegExp)
    }

    def getExecutionStrategy() {
        if ( usesRegExp ) {
             return new CronExecutionStrategy(this)
        } else {
            return new IntervalExecutionStrategy(this)
        }
    }

    static namedQueries = {
        active {
            eq 'enabled', true
        }
        inactive {
            eq 'enabled', false
        }
    }
}

product/InspectorGadget/grails-app/controllers/inspector/gadget/cms/DashboardController.groovy
package inspector.gadget.cms

import dto.view.dashboard.ApplicationSanity
import dto.view.dashboard.GlobalDashboardDTO
import dto.view.dashboard.JobSanity
import dto.view.dashboard.MonthlyJobSanity
import inspector.gadget.Application
import inspector.gadget.SystemConfiguration
import inspector.gadget.job.Job
import inspector.gadget.job.JobInstance
import inspector.gadget.util.DateUtil
import model.status.JobStatus

class DashboardController extends CmsController {

    def index() {
        redirect(action: "global")
    }

    def application() {
        def applicationId = params?.applicationId
        def application = Application.findById(Long.valueOf(applicationId))
        def applicationSanity = new ApplicationSanity(application: toViewDTO(application))

        def jobs = Job.findAllByApplication(application)

        if (!jobs.isEmpty()) {
            jobs.each { job ->
                if (job.hasInstances()) {
                    def errors = JobInstance.countByJobAndStatus(job, JobStatus.ERROR)
                    def success = JobInstance.countByJobAndStatus(job, JobStatus.OK)
                    def pending = JobInstance.countByJobAndStatus(job, JobStatus.PENDING)
                    def warnings = JobInstance.countByJobAndStatus(job, JobStatus.WARNING)
                    applicationSanity.addJobSanity(new JobSanity(error: errors, success: success, pending: pending, warning: warnings, jobName: job.name, jobId: job.id))
                }
            }
        }

        withFormat {
            html { [instance: applicationSanity, applicationList: toCollectionDTO(Application.list())] }
            json {
                response.setContentType("application/json")
                renderJSON(applicationSanity)
            }
        }
    }

    def job() {
        def jobId = params?.jobId
        def job = Job.findById(Long.valueOf(jobId))
        def jobList = Job.findAll()
        def currentMonth = params.currentMonth ?: (Calendar.getInstance().get(Calendar.MONTH) + 1)
        def startDate
        def endDate
        def monthlySanity

        if ( params.currentMonth != null && params.currentMonth.isNumber() ) {
            startDate = DateUtil.firstDayOfMonth(Integer.valueOf(currentMonth))
            endDate = DateUtil.lastDayOfMonth(Integer.valueOf(currentMonth))
            monthlySanity = MonthlyJobSanity.forMonth(Integer.valueOf(params.currentMonth))
        } else {
            startDate = DateUtil.firstDayOfCurrentMonth()
            endDate = Calendar.getInstance().getTime()
            currentMonth = (Calendar.getInstance().get(Calendar.MONTH) + 1)
            monthlySanity = MonthlyJobSanity.forCurrentMonth()
        }

        def instances = JobInstance.findAllByJobAndStartedAtBetween(job, startDate, endDate)

        monthlySanity.jobName = job.name
        instances.each { jobInstance ->
            def dailyJobSanity = monthlySanity.getJobSanityFor(jobInstance.startedAt)
            if (jobInstance.status.equals(JobStatus.ERROR)) { dailyJobSanity?.addError() }
            if (jobInstance.status.equals(JobStatus.WARNING)) { dailyJobSanity?.addWarning() }
            if (jobInstance.status.equals(JobStatus.OK)) { dailyJobSanity?.addSuccess() }
            if (jobInstance.status.equals(JobStatus.PENDING)) { dailyJobSanity?.addPending() }
        }

        withFormat {
            html { [instance: monthlySanity, jobList: toCollectionDTO(jobList), currentMonth: currentMonth] }
            json {
                response.setContentType("application/json")
                renderJSON(monthlySanity)
            }
        }
    }

    def global() {
        def globalDashboard = new GlobalDashboardDTO()
        def refreshRate = SystemConfiguration.findByKey("config.dashboard.refresh").valueAsInteger()
        def daysBefore  = SystemConfiguration.findByKey("config.dashboard.daysBefore").valueAsInteger()

        def from = DateUtil.substractDaysTo(daysBefore, Calendar.getInstance().getTime())
        def to = Calendar.getInstance().getTime()

        def lastFailures = JobInstance.findAllByStatusAndStartedAtBetween(JobStatus.ERROR, from, to, [sort: "id", order: "desc", max: 10])
        lastFailures.each { failure -> globalDashboard.addJobFailure(toViewDTO(failure)) }

        Application.list().each { application ->
            def count = Job.countByApplication(application)
            def failures = JobInstance.countByApplicationAndJobStatus(application, JobStatus.ERROR)
            if (count > 0) {
                globalDashboard.setJobCountFor(toViewDTO(application), count.intValue(), failures)
            }
        }

        withFormat {
            html {
                [dashboardInstance: globalDashboard, refreshRate: refreshRate] }
            json {
                response.setContentType("application/json")
                renderJSON(globalDashboard)
            }
        }
    }
}

product/InspectorGadget/grails-app/views/dashboard/global/_appCountChart.gsp
<%@ page import="dto.view.dashboard.ApplicationJobsDTO" %>
<div class="span5">
    <div id="jobCountByAppContainer" class="jobChart" style="min-width: 200px; height: 300px;"></div>
    <script>
        $(function () {
            $('#jobCountByAppContainer').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false
                },
                title: {
                    text: '<p class="text-info text-center">Job Count by Application</p>'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage}%</b>',
                    percentageDecimals: 1
                },
                colors: ['#3366cc', '#109618', '#ff9900', '#dc3912', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: false
                        },
                        showInLegend: true
                    }
                },
                series: [
                    {
                        type: 'pie',
                        point: {
                            events: {
                                click: function (e) {
                                    var target = e.currentTarget;
                                    var url = "${createLink(controller: "dashboard", action: "application", absolute: true)}?applicationId=" + target.id;
                                    window.location.href = url;
                                }
                            }
                        },
                        name: 'Events',
                        data: [
                            <% for (ApplicationJobsDTO appJobs : dashboardInstance.applicationJobs) { %>
                              { name: '${appJobs.application.name}', y: ${appJobs.jobCount} , id: ${appJobs.application.id} },
                            <% } %>
                        ]
                    }
                ]
            });
        });
    </script>
</div>

product/InspectorGadget/grails-app/views/dashboard/global/_lastErrors.gsp
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <g:sortableColumn property="id" title="${message(code: 'jobFailure.id.label', default: 'Id')}"/>
        <g:sortableColumn property="jobName" title="${message(code: 'jobFailure.name.label', default: 'Job Name')}"/>
        <g:sortableColumn property="applicationName" title="${message(code: 'jobFailure.applicationName.label', default: 'Application Name')}"/>
        <g:sortableColumn property="endDate" title="${message(code: 'jobFailure.endDate.label', default: 'End Date')}"/>
        <g:sortableColumn property="reason" title="${message(code: 'jobFailure.reason.label', default: 'Reason')}"/>
    </tr>
    </thead>
    <tbody>
    <g:each in="${dashboardInstance.lastFailures}" var="jobFailure">
        <tr>
            <td><g:link controller="jobInstance" action="show" id="${jobFailure.id}">${fieldValue(bean: jobFailure, field: "id")}</g:link></td>
            <td><g:link controller="dashboard" action="job" params="${[jobId: jobFailure.jobId]}">${fieldValue(bean: jobFailure, field: "jobName")}</g:link></td>
            <td><g:link controller="dashboard" action="application" params="${[applicationId: jobFailure.applicationId]}">${fieldValue(bean: jobFailure, field: "applicationName")}</g:link></td>
            <td><g:formatDate date="${jobFailure.endDate}" format="dd-MM-yyyy mm:ss:" /></td>
            <td><util:formatString max="40" string="${fieldValue(bean: jobFailure, field: "reason")}" /></td>
        </tr>
    </g:each>
    </tbody>
</table>

product/InspectorGadget/grails-app/views/dashboard/global/_lastErrorsChart.gsp
<%@ page import="dto.view.dashboard.ApplicationJobsDTO" %>
<div class="span5">
    <div id="errorCountByAppContainer" class="jobChart" style="min-width: 200px; height: 300px;"></div>
    <script>
        $(function () {
            $('#errorCountByAppContainer').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false
                },
                title: {
                    text: '<p class="text-info text-center">Error Count by Application</p>'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage}%</b>',
                    percentageDecimals: 1
                },
                colors: ['#3366cc', '#109618', '#ff9900', '#dc3912', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: false
                        },
                        showInLegend: true
                    }
                },
                series: [
                    {
                        type: 'pie',
                        point: {
                            events: {
                                click: function (e) {
                                    var target = e.currentTarget;
                                    var url = "${createLink(controller: "dashboard", action: "application", absolute: true)}?applicationId=" + target.id;
                                    window.location.href = url;
                                }
                            }
                        },
                        name: 'Events',
                        data: [
                            <% for (ApplicationJobsDTO appJobs : dashboardInstance.applicationJobs) { %>
                              { name: '${appJobs.application.name}', y: ${appJobs.failuresCount} , id: ${appJobs.application.id} },
                            <% } %>
                        ]
                    }
                ]
            });
        });
    </script>
</div>